/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/


function fiboEvenSum(n) {
  let fib = [1, 2]
  let counter = 0
  while(fib[fib.length-1] < n){
    let result = fib[counter] + fib[counter+1]
    fib.push(result)
    counter++
  }

  let sum = 0;
  for(let i = 0; i < fib.length; i++){
    if(fib[i] % 2 === 0){
      sum += fib[i]
    }
  }

  return sum;
}

fiboEvenSum(10)
